account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.home, name='home'),
    path('account/', views.restaurant_account, name='restaurant_account'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('register/', views.register, name='register'),
    path('register/done/', views.done, name='done'),
    path('logout/', auth_views.LogoutView.as_view(template_name='common/logout.html'), name='logout'),
    path('password_change/', views.password_change, name='password_change'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("common.urls")),
    path('', include("restaurant.urls")),
    path('', include("account.urls")),
]

restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.home, name='home'),
    path('rest/<int:restaurant_id>/', views.restaurant_detail, name='restaurant_detail'),
    path('rest/review/<int:restaurant_id>/', views.restaurant_review, name='restaurant_review'),

]

account/models.py
from django.db import models

# Create your models here.

common/models.py
from django.db import models

# Create your models here.

restaurant/models.py
from django.db import models
from django.db.models import Avg
from django.utils import timezone


class Restaurant(models.Model):
    id = models.AutoField(primary_key=True)
    restaurant_name = models.CharField(max_length=20)
    location = models.CharField(max_length=100)
    event = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return self.restaurant_name

class Menu(models.Model):
    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, default='')
    menu_name = models.TextField(max_length=150)
    date = models.DateField(default=timezone.now)
    

class Review(models.Model):
    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    review_text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    rating = models.FloatField(default=0, blank=True)
    
    def __str__(self):
        return self.menu_name
    
    @staticmethod
    def calculate_average_rating():
        average_rating = Menu.objects.aggregate(Avg('rating')) ['rating_avg']
        if average_rating is not None:
            average_rating = round(average_rating, 2)
        return average_rating

class SuggestionBoard(models.Model):
    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    post_content = models.TextField()

account/forms.py
from django import forms
from django.db import models
from restaurant.models import Menu 

class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu 
        fields = ['restaurant','date', 'menu_name']

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
    model = User
    fields = ('username', 'password1', 'password2')

restaurant/forms.py
from django import forms
from .models import Review

class RatingForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review_text', 'rating']
        widgets = {
            'rating': forms.RadioSelect(choices=[
                (5, '⭐⭐⭐⭐⭐'),
                (4, '⭐⭐⭐⭐'),
                (3, '⭐⭐⭐'),
                (2, '⭐⭐'),
                (1, '⭐'),
            ]),
            'review_text': forms.Textarea(attrs={'rows': 6, 'cols': 50, 'style': 'resize: none;'})
        }

account/views.py
from django.shortcuts import redirect, render
from restaurant.models import Restaurant, Menu, SuggestionBoard
from .forms import MenuForm

# Create your views here.
def restaurant_account(request):
    if request.method == "POST":
        form = MenuForm(request.POST)
        if form.is_valid():
            restaurant_name=form.cleaned_data['restaurant']
            form.save()
            return redirect('account:restaurant_account')
    else:
        form = MenuForm()
        
    return render(request, 'account/restaurant_account.html', {'form': form})


def home(request):
    return render(request, 'base.html')

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, update_session_auth_hash
from .forms import UserForm
from django.contrib.auth.forms import PasswordChangeForm

# def register(request):
#     if request.method == 'POST':
#         form = UserForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#         return redirect('common:done')
#     else:
#         form = UserForm()
#     return render(request, 'common/register.html', {'form': form})

def register(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('common:done')
    else:
        form = UserForm()
    return render(request, 'common/register.html', {'form': form})

def done(request):
    return render(request, 'common/done.html')

def password_change(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('common:password_change_done')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'common/password_change.html', {'form':form})

def password_change_done(request):
    return render(request, 'common/password_change_done.html')

restaurant/views.py
from django.shortcuts import render, redirect
from .models import Restaurant, Menu, Review
from django.utils import timezone
from restaurant.forms import RatingForm

def home(request):
    today = timezone.now().date()
    restaurant_name = Restaurant.objects.all()
    menu = Menu.objects.filter(date=today)
    context = {
        'restaurant_name' : restaurant_name,
        'menus' : menu
    }
    return render(request, 'home.html', context)


def restaurant_detail(request, restaurant_id):
    restaurants = Restaurant.objects.get(id=restaurant_id)
    # rating = Review.objects.get(restaurant=restaurants)
    reviews = Review.objects.order_by('-created_at') # 이거 바꿈. 원래는 all()
    context = {
        'restaurants': restaurants,
        'reviews' : reviews,
        # 'rating' : rating,
        }
    return render(request, 'restaurant_detail.html', context)

def restaurant_review(request, restaurant_id):
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('restaurant_detail', restaurant_id)
    else:
        form = RatingForm()

    rating = Restaurant.objects.all()
    
    reviews = Review.objects.all()
    context = {
        'rating': rating,
        'reviews': reviews,
        'form': form,
    }
    return render(request, 'restaurant_review.html', context)

# def restaurant_review(request):
#     if request.method == 'POST':
#         form = RatingForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('restaurant_review')
#     else:
#         form = RatingForm()

#     rating = Restaurant.objects.all()
#     reviews = Review.objects.all()
#     context = {
#         'rating': rating,
#         'reviews': reviews,
#         'form': form,
#     }
#     return render(request, 'restaurant_review.html', context)


# def restaurant_review(request):
#     rating = Restaurant.objects.all()
#     reviews = Review.objects.all()
#     context = {
#         'rating' : rating,
#         'reviews' : reviews
#     }
#     return render(request, 'restaurant_review.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <title>미니언즈 식단</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body style="padding-top:90px;">
    {% include 'navbar.html' %}

    {% block content %}
    
    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/c998a172fe.js"></script>
    <style media="all" id="fa-v4-shims"></style>
</body>
</html>

templates/common/done.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Registration Completed Successfully</h1> 
        <br>
        <p>Thank you for registering.</p> 
        <p class="font-italic"><a href="/login/">Log in</a> </p>  
    </div>
{% endblock %}

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Please Login</h1>
        <p class="font-italic">Please enter your id and password.</p>

        {% include "form_errors.html" %}
        
        <form action="{% url 'common:login' %}" method="post" class="card pt-3">
            {% csrf_token %}
            <div class="form-group row">
                <label class="col-form-label col-sm-2 ml-3 font-weight-bold" for="id_username">Restaurant name:</label>
                <div class="col-sm-5">
                    <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" class="form-control" required="" id="id_username">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label col-sm-2 ml-3 font-weight-bold" for="id_password">Password:</label>
                <div class="col-sm-5">
                    <input type="password" name="password" autocomplete="current-password" class="form-control" required="" id="id_password">
                </div>
            </div>

            <div class="form-group">
                <div class="offset-sm-2 col-sm-5">
                    <input type="submit" value="Log in" class="btn btn-info">
                    <input type="hidden" name="next" value="">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/common/logout.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Logged out</h1>
        <br>
        <div>
            <i class="fas fa-quote-left" aria-hidden="true"></i>
            <span class="h6"> Thanks for spending your quality time with this web site today. </span>
            <i class="fas fa-quote-right" aria-hidden="true"></i>
        </div>
        <p class="font-italic"><a href="/accounts/login/">Log in again</a></p>
    </div>
{% endblock %}

templates/common/password_change.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Password change</h1>
        <p class="font-italic">Please enter your old password for security's sake,
            and then enter your new password twice.</p>
        <form action="." method="post" class="card pt-3">
            {% csrf_token %}
            <div class="form-group row">
                <label class="col-form-label col-sm-3 ml-3 font-weight-bold" for="id_old_password">Old password:</label>
                <div class="col-sm-5">
                    <input type="password" name="old_password" autocomplete="current-password" autofocus="" class="form-control" required="" id="id_old_password">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label col-sm-3 ml-3 font-weight-bold" for="id_new_password1">New password:</label>
                <div class="col-sm-5">
                    <input type="password" name="new_password1" autocomplete="new-password" class="form-control" required="" id="id_new_password1">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label col-sm-3 ml-3 font-weight-bold" for="id_new_password2">New password confirmation:</label>
                <div class="col-sm-5">
                    <input type="password" name="new_password2" autocomplete="new-password" class="form-control" required="" id="id_new_password2">
                </div>
            </div>
    
            <div class="form-group">
                <div class="offset-sm-3 col-sm-5">
                    <input type="submit" value="Password change" class="btn btn-info">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/common/password_change_done.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Password change successful</h1> 
        <br>
        <p>Your password was changed!</p> 
    </div>
{% endblock %}

templates/common/register.html
{% extends 'base.html' %}
{% block content %}
        <div class="container">
            <h1>New User Registration</h1>
            <p class="font-italic">Please enter your username and password twice.</p>
            <form action="." method="post" class="card pt-3">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 ml-3 font-weight-bold" for="id_username">Restaurant name:</label>
                    <div class="col-sm-5">
                        <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" class="form-control" required="" id="id_username"  value="{{ form.id_username.value|default_if_none:'' }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 ml-3 font-weight-bold" for="id_password1">Password:</label>
                    <div class="col-sm-5">
                        <input type="password" name="password1" autocomplete="new-password" class="form-control" required="" id="id_password1"  value="{{ form.id_password1.value|default_if_none:'' }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 ml-3 font-weight-bold" for="id_password2">Password confirmation:</label>
                    <div class="col-sm-5">
                        <input type="password" name="password2" autocomplete="new-password" class="form-control" required="" id="id_password2"  value="{{ form.id_password2.value|default_if_none:'' }}">
                    </div>
                </div>
                <div class="form-group">
                    <div class="offset-sm-3 col-sm-5">
                        <input type="submit" value="Register" class="btn btn-info">
                    </div>
                </div>
            </form>
        </div>
    </body>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Today's Menu</h1>
    <div class="container text-center" style='width:1000px'>
    <ul style="padding: 80px;">
        {% for menu in menus %}
            <h2 class="font-weight-bold"><a href="{% url 'restaurant:restaurant_detail' menu.id %}">{{ menu.restaurant.restaurant_name }}</a></h2>
            <br>
            <div class="rate">
                <span style="width: 50%">별점 {{ menu.rating }}</span>
            </div>
            <p class="fs-1" style="padding-bottom: 50px;">{{ menu.menu_name }}</p>
        {% endfor %}
    </ul>
    </div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary fixed-top">
    <span><a class="navbar-brand mx-3 mb-0 font-weight-bold" href="/">미니언즈</a></span>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarSupportedContent" style>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-secondary">
                <a class="nav-link text-white" href="/menu/">메뉴</a>
            </li>
            <li class="nav-item mx-1 btn btn-secondary">
                <a class="nav-link text-white" href="/restaurant/">식당</a>
            </li>
            <li class="nav-item dropdown mx-1 btn btn-secondary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">계정</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="/account/">식당</a>
                    <hr class="dropdown-divider">
                    <a class="dropdown-item" href="/admin/">관리자</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-secondary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
            	    <i class="fas fa-user" aria-hidden="true"></i>
                    {% if user.is_authenticated %}
                    {{ user.username }}
                    {% else %}
                    손님
                    {% endif %}
                </a>
                <div class="dropdown-menu">
                    {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'common:logout' %}">로그아웃</a>
                    {% else %}
            	    <a class="dropdown-item" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'common:password_change' %}">비밀번호 변경</a>
                    {% else %}
            	    <a class="dropdown-item" href="{% url 'common:register' %}">회원가입</a>
                    {% endif %}
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/restaurant_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-5 text-left" style='width:500px'>
    <div>
        <h1 class="font-weight-bold">{{ restaurants.restaurant_name }}</h1>
        <h3 style="margin-top: 30px;">{{ restaurants.location }}</h3>
        <h3 style="margin-top: 30px;">{{ restaurants.event }}</h3>
    </div>

    {% comment %} <h1>{{ restaurant.restaurant_name }}</h1> {% endcomment %}
    <div>
        {% for reviews in reviews %}
        <table class="table">
            <tr>
                <td>{{ menu.rating }}</td>
            </tr>
            <tr>
                <td>{% include 'review_list.html' %}</td>
            </tr>
        </table>
    </div>
    {% endfor %}
    
<div class="text-lg-end text-right">
    <a href="{% url 'restaurant:restaurant_review' restaurant.id %}" class="btn btn-success">리뷰 작성하기</a>
</div>
{% endblock %}

templates/restaurant_review.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-center" style='width:1000px'>
    <div>
    <form name="myform" id="myform" method="post">
        {% csrf_token %}
        <fieldset>
            <legend class="font-weight-bold container mt-5 text-left" style='width:500px'>Review</legend>
            <input type="radio" name="rating" value="5" id="rate1"><label for="rate1">⭐</label>
            <input type="radio" name="rating" value="4" id="rate2"><label for="rate2">⭐</label>
            <input type="radio" name="rating" value="3" id="rate3"><label for="rate3">⭐</label>
            <input type="radio" name="rating" value="2" id="rate4"><label for="rate4">⭐</label>
            <input type="radio" name="rating" value="1" id="rate5"><label for="rate5">⭐</label>
        </fieldset>
    
    {{ form.review_text }}
    </div>
    <div class="text-lg-end text-right">
    <button type="submit" class="btn btn-success">리뷰 등록</button>
    </div>
    </form>
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/c998a172fe.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style media="all" id="fa-v4-shims"></style>
    <style>
        #myform fieldset{
            display: inline-block;
            border: 0;
        }
        #myform input[type=radio]{
            display: none;
        }
        #myform label{
            font-size: 3em;
            color: transparent;
            text-shadow: 0 0 0 #f0f0f0;
        }
        #myform label:hover{
            text-shadow: 0 0 0 #ffff00 ; /* 마우스 호버 */
        }
        #myform label:hover ~ label{
            text-shadow: 0 0 0 #ffff00 ; /* 마우스 호버 뒤에오는 이모지들 */
        }
        #myform fieldset{
            display: inline-block; /* 하위 별점 이미지들이 있는 영역만 자리를 차지함.*/
            direction: rtl; /* 이모지 순서 반전 */
            border: 0; /* 필드셋 테두리 제거 */
        }
        #myform fieldset legend{
            text-align: left;
        }
        #myform input[type=radio]:checked ~ label{
            text-shadow: 0 0 0 #ffff00 ; /* 마우스 클릭 체크 */
        }
    </style>
{% endblock %}

templates/review_list.html
{% block content %}

{% if reviews %}
    <ul>
    {% for reviews in reviews %}
        <li><a>{{ review.review_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>리뷰가 없습니다.</p>
{% endif %}

{% endblock %}